# Example configuration for the SWE-agent runtime.
# Adjust paths and environment variable values to match your setup.

agent:
  model:
    name: azure/gpt-4o
    api_key: ${AZURE_API_KEY}
    api_base: ${AZURE_API_BASE}
    temperature: 0.6

  security:
    blocked_commands:
      - rm
      - pip
      - git
      - sudo

  limits:
    max_tokens: 50000
    max_steps: 30

  templates:
    system_template: |-
      You are an autonomous programmer working in a Singularity container.
      Execute bash commands and submit solutions when done.

  mcp:
    path: /opt/mcp/filesystem/server
    tool_allowlist:
      - read_file
      - write_file
      - list_directory
    env:
      MCP_LOG_LEVEL: info
    use_structured_content: false

  commands:
    apptainer_image: ./swebench_instances/images/swebench.sif
    working_directory: /workspace
    bind_mounts:
      - /host/data:/workspace/data
      - /host/cache:/workspace/.cache
    env:
      SWE_BENCH_DATASET: /workspace/data/swe-bench

